### ISSUE TITLE
$cordovaSQLite Mocks needed for Unit Testing. 

### ISSUE THREAD

**Issue by scripterkaran** [driftyco/ng-cordova#1001]
Is there any roadmap where this will be implemented ?

**Comment by Ionitron** [comment]
Greetings @scripterkaran!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
