### ISSUE TITLE
Documentation error on Device-Motion

### ISSUE THREAD

**Issue by jonalling** [driftyco/ng-cordova#1002]
Documentation lists this as the installation line,

    cordova plugin add org.apache.cordova.device-motion

But it should be this according to the official docs and a warning during installation,

    cordova plugin add cordova-plugin-device-motion

**Comment by Ionitron** [comment]
Greetings @jonalling!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
