### ISSUE TITLE
can't pass parameters with file transfer Plugin Parameter at http://ngcordova.com/docs/plugins/fileTransfer/

### ISSUE THREAD

**Issue by mayurbaldha** [driftyco/ng-cordova#1012]
at https://github.com/apache/cordova-plugin-file-transfer i can pass parameters {value1:test,value2:param}
with image File

var win = function (r) {
    console.log("Code = " + r.responseCode);
    console.log("Response = " + r.response);
    console.log("Sent = " + r.bytesSent);
}

var fail = function (error) {
    alert("An error has occurred: Code = " + error.code);
    console.log("upload error source " + error.source);
    console.log("upload error target " + error.target);
}

var options = new FileUploadOptions();
options.fileKey = "file";
options.fileName = fileURL.substr(fileURL.lastIndexOf('/') + 1);
options.mimeType = "text/plain";

var params = {};
params.value1 = "test";
params.value2 = "param";

options.params = params;

var ft = new FileTransfer();
ft.upload(fileURL, encodeURI("http://some.server.com/upload.php"), win, fail, options);

 whereas in http://ngcordova.com/docs/plugins/fileTransfer/

I can't use params with file upload.. Seems to be bug in ngCorodva plugin

**Comment by Ionitron** [comment]
Greetings @mayurbaldha!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by KowsalyaPK** [comment]
Can you say me how the http post method works? How does it pass file to the server? What parameters does it use?
