### ISSUE TITLE
 listEventinRange Odd Date Return

### ISSUE THREAD

**Issue by mario-aleo** [driftyco/ng-cordova#1016]
Hello,

I wish to know what is the type of the dates callback from listEventinRange, i'm receiving odd numbers, but I need to show this information.

Thanks.

**Comment by Ionitron** [comment]
Greetings @mario-aleo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
