### ISSUE TITLE
Custom build is not injecting correct modules

### ISSUE THREAD

**Issue by jonathanpalma** [driftyco/ng-cordova#1021]
I tryed to build my own ngCordova module to avoid load some modules I won't use. So, I used the official site <a href="http://ngcordova.com/build/">ngCordova: Custom Build</a> but when I inject the ngCordova it was showing this 

![screenshot from 2015-10-09 11 09 27](https://cloud.githubusercontent.com/assets/12414771/10400491/3f7587d4-6e76-11e5-86b8-9254ba3c7ff8.png)

I could see that ngCordova.plugins module injector was injecting the plugin like this
```javascript
angular.module('ngCordova.plugins', [
   'camera',
   'geolocation',
   'localNotification',
   'media',
   'nativeAudio',
   'network',
   'vibration'
]);
```
But modules are defined like
```javascript
angular.module('ngCordova.plugins.camera', [])
angular.module('ngCordova.plugins.geolocation', [])
.
.
.
angular.module('ngCordova.plugins.vibration', [])
```

I fixed using
```javascript
angular.module('ngCordova.plugins', [
   'ngCordova.plugins.camera',
   'ngCordova.plugins.geolocation',
   'ngCordova.plugins.localNotification',
   'ngCordova.plugins.media',
   'ngCordova.plugins.nativeAudio',
   'ngCordova.plugins.network',
   'ngCordova.plugins.vibration'
]);
```

**Comment by Ionitron** [comment]
Greetings @jonathanpalma!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
