### ISSUE TITLE
How Can i use com.doogle.audiotoggle plugin with ngCordova?

### ISSUE THREAD

**Issue by tezlopchan** [driftyco/ng-cordova#1031]
How Can i use com.doogle.audiotoggle plugin with ngCordova?

**Comment by Ionitron** [comment]
Greetings @tezlopchan!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
