### ISSUE TITLE
Instagram sharing

### ISSUE THREAD

**Issue by SergeyKuzmich** [driftyco/ng-cordova#1037]
Hi

I'm using $cordovaInstagram for sharing images captured from camera or chosen from library.
And I found a strange behavior (may be bug):
I use input:file to choose image, it goes to web-server (script makes watermark on image), than it returns as base64 string and I send it to Instagram. It works fine when I choose image from library to upload, but when I capture image $cordodaInstagram opens Instagram and Instagram fails.

Does anyone has any suggestions to resolve it?

**Comment by Ionitron** [comment]
Greetings @SergeyKuzmich!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by SergeyKuzmich** [comment]
Hi

Issue is not fixed, I guess, but I know that it is issue of Instagram Plugin. By docs it requires base64 encoded image and there is no note that image must have PNG type. The problem appears when I tried to give plugin encoded JPG image.

Thank you.
