### ISSUE TITLE
Hi guys is there a pdf417 scanner plugin on the ionic framework?

### ISSUE THREAD

**Issue by shepherdsid** [driftyco/ng-cordova#221]

**Comment by bgold0** [comment]
Has anyone been able to get pdf417-phonegap to work on Ionic? [I haven't been able to figure it out.](http://stackoverflow.com/questions/30132924/calling-pdf417-phonegap-cordova-plugin-in-ionic)

**Comment by sellcorpllc** [comment]
[pdf417-phonegap](https://github.com/PDF417/pdf417-phonegap) is not a free library. They have their own [website](http://pdf417.mobi/) where an individual can register for license keys. The license keys are parameters in their scan function and control the functionality of the plugin. In order to use the library the widget id the config.xml needs to be mobi.pdf417.demo. This widget id in config.xml is used in the license key generation process, and if the license keys don't match the widget id, the application will throw an error.
