### ISSUE TITLE
Error: init not called with valid version - Facebook Connect

### ISSUE THREAD

**Issue by tombeech** [driftyco/ng-cordova#615]
Hi,

I'm trying to use the ngConnect FB connect option like the following:

<div id="fb-root"></div>
    <script src='js/facebookConnectPlugin.js'></script>
    
    <script src="lib/ngCordova/dist/ng-cordova.js"></script>
    <script src="cordova.js"></script>

//App.js
```javascript
.config(function ($stateProvider, $urlRouterProvider, $cordovaFacebookProvider) {

        if (!window.cordova) {
            var appID = 1412200522411443;
            var version = "v2.0"; // or leave blank and default is v2.0
            $cordovaFacebookProvider.browserInit(appID, version);
        }
}
```
//contoller 
```javascript
.controller('DashCtrl', function ($scope, $cordovaFacebook, $log) {
        $scope.getLoginStatus = function () {
            $cordovaFacebook.getLoginStatus().then(function (status) {
                $scope.status = status;
            }, function (error) {
                $scope.status = error;
            })
        };

        $scope.login = function () {
            $cordovaFacebook.login(["public_profile"]).then(function (success) {
                $scope.loginInfo = success;
            }, function (error) {
                $scope.error = error;
                alert(error);
            })
        };


        $scope.logout = function () {
            $cordovaFacebook.logout().then(function (success) {
                console.log(success);
            }, function (error) {
                $scope.error = error;
                alert(error);
            })
        };

        $scope.getMe = function () {
            $scope.me = ["refreshing..."];
            $cordovaFacebook.api("me", null).then(function (success) {
                $scope.me = success;
            }, function (error) {
                $scope.error = error;
            })
        };
    })

```

However, I get the error when i click login:

launching FB SDK
Error: init not called with valid version
Error
    at Object.<anonymous> (http://connect.facebook.net/en_US/sdk.js:38:148)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:588)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550)
    at window.FB.require (http://connect.facebook.net/en_US/sdk.js:16:550) ionic.bundle.js:19387

**Comment by moglash** [comment]
I has the same error. Any solution or workaround to this?

**Comment by vasconcelloslf** [comment]
same here.

**Comment by pensiero** [comment]
did you solve?

**Comment by raphaelduartepinheiro** [comment]
@pensiero @vasconcelloslf @barczaG @tombeech 
I have the same issue since I updated my Android platform for Cordova 5.0, then all request were failing, I needed to install  `cordova plugin add cordova-plugin-whitelist`
Facebook integration via Cordova comes to life after that. But in console, Cordova asks for meta tag from Content Security Policy. When I do, I get the error of this issue... Without meta tag (but with warnings) it works perfectly. Maybe it's a lack of meta tag attribute option...

**Comment by gortok** [comment]
Interesting. Sounds like an issue with the underlying plugin and not ngCordova?

**Comment by raphaelduartepinheiro** [comment]
@gortok I don't know if it's **exactly** the same issue as the issue's author.

I'd appreciate to read a feedback about this from him. If you don't mind... :)

**Comment by robson-jardim** [comment]
Same here...
Hard to find some tip to fix it...

**Comment by gijo-varghese** [comment]
I had the same problem, and I think I found the root cause!

### Root cause
In my case, we were injecting FB SDK dynamically to our customer's website. However, some of our customers were already added FB SDK via other plugins. Those plugins have different app id and version.

**So depending on latency some plugins call `init` before/after ours**

### Solution
If you're the owner of the site where you're injecting the SDK, make sure no other plugins are injecting FB SDK and calling `init` different version and app id

If you don't own the site, then at least try to inject the SDK before anyone else and prefer `not async`

I also reported the same to FB. They told not to call init separately, pass init params directly in the rule. I've attached the code that I use:

```javascript
if (!document.getElementById("fb-root")) {
      // create div required for fb
      const fbDiv = document.createElement("div");
      fbDiv.id = "fb-root";
      document.body.appendChild(fbDiv);
      // Run any script after sdk is loaded
      window.fbAsyncInit = () => {
        //
      };
      // inject sdk.js
      (function(d, script) {
        script = d.createElement("script");
        script.type = "text/javascript";
        script.async = true;
        script.src =
          "https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2&appId=" +
          process.env.REACT_APP_FB_APP_ID +
          "&autoLogAppEvents=1";
        d.getElementsByTagName("head")[0].appendChild(script);
      })(document);
    }

```
