### ISSUE TITLE
Add Mock for $cordovaLocalNotification

### ISSUE THREAD

**Issue by w3apps** [driftyco/ng-cordova#716]
Add the $cordovaLocalNotification plugin to the ngCordovaMocks module.

**Comment by gortok** [comment]
If you could create a pull request with the mocks for this; that'd be helpful.  Since there are a number of plugins we support, we rely on individual contributions to keep the project going.   Otherwise it'd be one of those "When we're able to get to it" sort of things, which may be different than your time table.
