### ISSUE TITLE
Problems to setup Facebook Plugin in the browser

### ISSUE THREAD

**Issue by felquis** [driftyco/ng-cordova#731]
I'm getting this error: 

```
TypeError: Cannot read property 'browserInit' of undefined
```

I'm using this: 
```js
// Only required for development in browser, not cordova!
module.config(function($cordovaFacebookProvider) {
  var appID = 123456789;
  var version = "v2.0"; // or leave blank and default is v2.0
  $cordovaFacebookProvider.browserInit(appID, version);
});
```

I'm trying to run the project with `cordova run browser`, so, I'm not sure what could be wrong.

**Comment by felquis** [comment]
I think `browserInit` need to be inside platform ready.

**Comment by felquis** [comment]
this.browserInit = function (id, version) {
      this.appID = id;
      this.appVersion = version || "v2.0";

      facebookConnectPlugin.browserInit(this.appID, this.appVersion);
    };

```js
    this.browserInit = function (id, version) {
      var appID = id;
      var appVersion = version || "v2.0";

      ionic.Platform.ready(function () {
        facebookConnectPlugin.browserInit(appID, appVersion);
      });
    };
```

**Comment by deliverymanager** [comment]
I had the exact same problem!
And solved it your way!
Well if you think about it, in the Ng-Cordova,  the FacebookCordovaProvider is called to initiate the FB SKD even before its files are launched.
I think this problem existed from the creation of the ng-cordova.
It is a bug related only to ng-cordova as if we used purely the facebook connect plugin that the ng-cordova uses, then this would not be an issue, as it doesn't use a provider to set the appid.

I really don't like editing the ng-cordova files to change this, but in this case it seems that there is no alternative in order to make it work!

I hope the source files of ng-cordova will be updated soon to fix this bug.

**Comment by tonypius** [comment]
Thanks man. Solved it the same way.

**Comment by blckshrk** [comment]
Hi,

@robotvert could you make a PR maybe?

**Comment by robotvert** [comment]
@blckshrk this issue is closed, hasn't the problem been fixed? in any case, sorry but I won't do a PR because I'm not using ionic or cordova anymore, it was a one time gig for me and frankly the experience was so miserable I'm definitely not going back.

**Comment by blckshrk** [comment]
@robotvert I dropped out the idea of using FB connect on web app... I use the simulator or connects the Chrome inspector to my smartphone. I think this is the more correct way to develop cordova apps. Thanks for your reply :)

**Comment by braianj** [comment]
Hello, can you specify the file that you modify?
