### ISSUE TITLE
Directories cannot be found if they contain + or - characters in their name. 

### ISSUE THREAD

**Issue by topless** [driftyco/ng-cordova#767]
Although this is a legit path for storing data etc ..
cordova.file.externalDataDirectory/+10/other_stuff

When I am trying `$cordovaFile.checkDir(cordova.file.externalDataDirectory, '+10').then(...)`
It returns Not Found error. If I replace the character '-' or '+' it is resolved properly. 
I went through the file plugin code but didn't spot out anything, so I am guessing it might have something to do with `resolveLocalFileSystemURL` of Cordova.

**Comment by gortok** [comment]
Thanks for sharing this. It could be  a bug in the underlying plugin; if you can provide code using the wrapper and just using the plugin without the wrapper and it turns out the bug is in the ngCordova code; we'll be happy to fix it. We don't really have the bandwidth to fork and fix the underlying plugins themselves.
