### ISSUE TITLE
On $cordovaOauth is not possible to change the callback url

### ISSUE THREAD

**Issue by ningod** [driftyco/ng-cordova#783]
It may be usefull to have an options parameter on  $cordovaOauth to set different callback urls

**Comment by nraboy** [comment]
In my parent repo, this is possible:

https://github.com/nraboy/ng-cordova-oauth

You would set `options.redirect_uri` to whatever you want, otherwise it will use the default of `http://localhost/callback`.  I haven't had a chance to merge this version of the library with Driftyco's ngCordova.

Regards,

**Comment by nraboy** [comment]
This was merged into the latest master.  @pbernasconi can close this ticket.
