### ISSUE TITLE
feat : List available Wifi networks

### ISSUE THREAD

**Issue by Solido** [driftyco/ng-cordova#797]
Currently we have plugin to monitor state of the current connection but none to list available wifi around.
There's some implementations out there but most only works on android phones. 
That would be a other stone to the great list of provided features.
Best Regards.

**Comment by gortok** [comment]
This would be great. If you have a plugin you can suggest; please include a link to it.  Also, if you could help us out by writing a wrapper, I list out how to do that in #885; otherwise I'll put it on the backlog once you've provided a link to a plugin that does this that we should write a wrapper for.
