### ISSUE TITLE
analytics not showing any data

### ISSUE THREAD

**Issue by Kratos-SA** [driftyco/ng-cordova#823]
I have implemented the analytics plugin but I am not seeing anything in my analytic dashboard. I have wrapped it in a device ready and I have it running on a device but I see nothing. Please can you document this a bit more or explain where I am going wrong.

document.addEventListener("deviceready", function () {
        $cordovaGoogleAnalytics.debugMode();
        $cordovaGoogleAnalytics.startTrackerWithId('UA-4381823-6');
        $cordovaGoogleAnalytics.setUserId(userID);
     });

thats in my master controller.

document.addEventListener("deviceready", function () {
        $cordovaGoogleAnalytics.trackView('Welcome');
        $cordovaGoogleAnalytics.trackEvent('Bookings', 'Click', 'Button', 100);
    });

and thats in my child controller.

**Comment by gortok** [comment]
If you could include a sample project that reproduces this issue, I'll be happy to take a closer look. Also specify which platform this is failing for (iOS, android).

**Comment by Ionitron** [comment]
Greetings @Kratos-SA!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
