### ISSUE TITLE
File listdir

### ISSUE THREAD

**Issue by pcrombach** [driftyco/ng-cordova#833]
The function listdir in $cordovaFile is marked out?
If I unmark it this function works???

**Comment by ctaepper** [comment]
was wondering the same thing...

**Comment by pcrombach** [comment]
After I incompetent listDir I use it in my app without problems, So.....

**Comment by ctaepper** [comment]
i use bower to handle dependencies, i am not able to edit the source files. of course i can always copy that part into my own code, but thats an antipattern..

**Comment by Ionitron** [comment]
Greetings @pcrombach!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
