### ISSUE TITLE
URIencode is enabled by default ($cordovaFileTransfer)

### ISSUE THREAD

**Issue by mjvdwater** [driftyco/ng-cordova#835]
URIencode is called by default on the url specified when calling the download or upload functions, unless you specify the encodeURI property in the options argument. The documentation states that the options argument currently only supports headers. This lead me to pull my hair out for a couple of days. Please update the documentation.

**Comment by gortok** [comment]
I'm really sorry that happened. We love PRs that help fix the docs; could you include a PR with the documentation fix? You're probably the best person to do it since you were just working on this issue.  I'll be happy to look over and merge the PR when it's ready.

**Comment by Ionitron** [comment]
Greetings @mjvdwater!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by Brad19** [comment]
Hi,
I find the issue with cordova file transfer when I tried to download the file from s3 and I found that the signature does not match due to % from the source is replace with %25. Please find my post in stackoverflow. Please check and Kindly advise. I've spent couple of days pulling my hair. Not sure what to do. http://stackoverflow.com/questions/38684415/could-not-download-image-with-s3-getsignedurlgetobject-and-returns-signatur. Please check and Kindly advise
