### ISSUE TITLE
Using the Cordova-SQLite-Plugin $scope.execute isn't running but the database is being opened without error

### ISSUE THREAD

**Issue by dcp3450** [driftyco/ng-cordova#837]
I have a database that is created when my Windows 8 app starts. When I tap a button on the screen I'm using ng-view to change the content. In the controller I want to do a call to my database to select data then I'll be using the results to populate the template that's pulled in with the ng-view.

I'm using the following code to open my db and select some items from the table. Console shows the database is being opened but the other logs don't run since the `$scope.execute` isn't ran. I don't get any js or app errors.

```
var nanoDB = $cordovaSQLite.openDB( "nanoDB.db" );

$scope.execute = function () {
    var query = "SELECT name FROM nanoProd";
    console.log(query);
    $cordovaSQLite.execute(nanoDB, query, []).then(function (res) {
        console.log(res);
    }, function (err) {
        console.log(err);
    });
};
```

I'm not use `$cordovaSQLite.openDB( {name:"nanoDB.db"} );` [per the docs](http://ngcordova.com/docs/plugins/sqlite/) because of solution in an [issue for Cordova-SQLite-Plugin](https://github.com/litehelpers/Cordova-sqlite-storage/issues/246).

Why isn't my execute running?

**Comment by bleuscyther** [comment]
this is the same error  : https://github.com/driftyco/ng-cordova/issues/651

**Comment by Ionitron** [comment]
Greetings @dcp3450!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
