### ISSUE TITLE
cordovaSocialSharing .share() is not definied

### ISSUE THREAD

**Issue by kgilmur** [driftyco/ng-cordova#838]
Cannot read property 'socialsharing' of undefined. In xcode shows as cordova error where "dataFromBase64String:base64content" is deprecated and suggests added cdv to create "cdv_dataFromBase64String:base64content" 

Not sure if this is a fix I can go in and manually do somehow? Or if I need to abandon this plugin. 

Direction would be greatly appreciated.

**Comment by CyrilSabbagh** [comment]
+1 same issue

**Comment by VincentPuget** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @kgilmur!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
