### ISSUE TITLE
New Method showWithOptions of PhoneGap Toast by Eddy Verbruggen dont work ngCordova/toast

### ISSUE THREAD

**Issue by alvaroziqar** [driftyco/ng-cordova#849]
Hi.

Looking at the plugin PhoneGap Toast by Eddy Verbruggen, the method showWithOptions available since 2.1.0 version is not implemented  in ngCordova / toast.

Thanks

**Comment by gortok** [comment]
If you include a PR that includes that enhancement, I'll be happy to include it.

**Comment by Ionitron** [comment]
Greetings @alvaroziqar!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by PyriteParrot** [comment]
+1

**Comment by gortok** [comment]
looks like i twas added here: https://github.com/driftyco/ng-cordova/pull/1170

just waiting for the OP to strip the dist/ from their PR.
