### ISSUE TITLE
Update http://ngcordova.com/docs/plugins/sqlite/ example

### ISSUE THREAD

**Issue by palpa** [driftyco/ng-cordova#852]
To:
```javascript
  var db = $cordovaSQLite.openDB( "my.db");

  // for opening a background db:
  var db = $cordovaSQLite.openDB( "my.db",  1 );
```
Instead of this:
```javascript
  var db = $cordovaSQLite.openDB({ name: "my.db" });

  // for opening a background db:
  var db = $cordovaSQLite.openDB({ name: "my.db", bgType: 1 });
```
Thanks!

**Comment by ritvick** [comment]
+1

**Comment by quanghoc** [comment]
+1

**Comment by Ionitron** [comment]
Greetings @palpa!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
