### ISSUE TITLE
Size of FileSystem

### ISSUE THREAD

**Issue by pcrombach** [driftyco/ng-cordova#858]
In former versions of ngCordova File there was the possibility to define the size of the FileSystem. Now it is gone. What size the FileSystem now will be?...

**Comment by Ionitron** [comment]
Greetings @pcrombach!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
