### ISSUE TITLE
Socket

### ISSUE THREAD

**Issue by NestorAlbelo** [driftyco/ng-cordova#863]
Hi,
I would like that this plugin was added to create a Socket

http://plugins.cordova.io/#/package/cz.blocshop.socketsforcordova

Thanks =D

**Comment by gortok** [comment]
If you write a PR that includes a wrapper for this; that'd ensure it'd get included much more quickly. Thanks!

**Comment by Ionitron** [comment]
Greetings @NestorAlbelo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
