### ISSUE TITLE
Wrong sample code in documentation

### ISSUE THREAD

**Issue by BipinBhandari** [driftyco/ng-cordova#870]
In [documentation](http://ngcordova.com/docs/plugins/sqlite/) object is passed when calling openDB.  

```
var db = $cordovaSQLite.openDB({ name: "my.db" });
  // for opening a background db:
  var db = $cordovaSQLite.openDB({ name: "my.db", bgType: 1 });
```

But in code:

  ```
openDB: function (dbName, background) {

        if (typeof background === 'undefined') {
          background = 0;
        }

        return $window.sqlitePlugin.openDatabase({
          name: dbName,
          bgType: background
        });
      }
```

It takes dbName and background as parameter. Please fix the documentation.

**Comment by gortok** [comment]
Thanks for catching this. Please submit a PR for this with the fixed documentation.

**Comment by Ionitron** [comment]
Greetings @BipinBhandari!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
