### ISSUE TITLE
InAppBrowser clears out code to a blank screen

### ISSUE THREAD

**Issue by dcp3450** [driftyco/ng-cordova#879]
I've installed `InAppBrowser` per the docs and included it in my app:

```
var nanoApp = angular.module('nanoApp', ['ngRoute', 'ngCordova']);

nanoApp
.config(function ($routeProvider, $compileProvider, $cordovaInAppBrowserProvider) {
    ...
}
```

I'm also using the SQLite plugin in conjunction with ngCordova.

When my app make a database call I get an error:
```
var nanoApp = angular.module('nanoApp', ['ngRoute', 'ngCordova']);

nanoApp
.config(function ($routeProvider, $compileProvider, $cordovaInAppBrowserProvider) {
```

Then my app's code is cleared out. If I comment out ngCordova I don't have the issue (but I can't work with my database).

Is there anything else I need to do?

**Comment by dcp3450** [comment]
I've found that if I run either one of these:

```var nanoDB = $cordovaSQLite.openDB("nanoDB.db");
    var nanoDB = window.sqlitePlugin.openDatabase({ name: "nanoDB.db" });
```

I get the error.

**Comment by mhartington** [comment]
Sounds like it's an issue with the sqlite plugin. Do you have this issue if you use the raw cordova api?

**Comment by Ionitron** [comment]
Greetings @dcp3450!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
