### ISSUE TITLE
[Feat] Add the plugins as submodules

### ISSUE THREAD

**Issue by matheusrocha89** [driftyco/ng-cordova#901]
@nraboy did a great pull request for `ng-cordova-oauth` on this project ( #841 ) adding it as a submodule, it's a great idea. Don't you think it's a better idea to do that with all the others plugins? Doing that it's better to make `ng-cordova` updated with all of them? What do you think

**Comment by nraboy** [comment]
Thanks for the compliment!  I'm not so certain this would work in all cases though.  I specifically designed `ng-cordova-oauth` for use with AngularJS, but others are wrapped inside ngCordova rather than the plugin itself.

Worth looking into though :-)

**Comment by matheusrocha89** [comment]
That's bad, :stuck_out_tongue: If we could do that it will be great, it will be easier to maintain updated.

**Comment by nraboy** [comment]
Agreed!  Puts less need for intervention on the plugin itself as changes will be automatically piped in.

**Comment by matheusrocha89** [comment]
Yes... If some of the other projects are like plugins, like yours, they could starting making pull requests doing that, putting their project on submodules here.

**Comment by gortok** [comment]
I like the idea, one issue is stability.

**Comment by matheusrocha89** [comment]
I believe there is at least one easy project to do that just as a kickstart to incentive the others

**Comment by nielskrijger** [comment]
This might be totally unrelated, but just a couple of hours ago our CI started failing:

```
Module 'ngCordovaOauth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

First time I saw this. 
Were there any changes made as part of this submodule request that might have caused it?

**Comment by AbdullahNasir** [comment]
we are also having the same issue as @nielskrijger

**Comment by pppglowacki** [comment]
We are also having the same issue as @nielskrijger

**Comment by tcrammond** [comment]
Also having the same problem as @nielskrijger

**Comment by matheusrocha89** [comment]
I opened a issue about it (#912) @nraboy I think you should take a look too.

**Comment by matheusrocha89** [comment]
I saw here that @nraboy already fix it, on the next release will works again.

**Comment by gortok** [comment]
I think we're going to collect more data on this; think of the oAuth module as the test subject.  We need to hold off on making this a wider thing until we've got a rock solid deployment and regression check process around submodules.

**Comment by matheusrocha89** [comment]
@gortok do you have something in mind how to do that on deployment?

**Comment by gortok** [comment]
@matheusrocha89 http://38.media.tumblr.com/8eb1eb849b8b5fb2452bb74a697900a0/tumblr_mzvc3qNsII1t7xe6go1_400.gif

**Comment by matheusrocha89** [comment]
hahahahahaha Ok @gortok . Well I am not an expert on it, but if you need any help I will do my best. @nraboy do you have any idea how to do that? :arrow_up:

**Comment by nraboy** [comment]
I personally don't use Gulp beyond ng-cordova, so I don't know how to do any regression checks with it.  Because we're using it for building and testing only, I think the best thing we could do in the immediate is switch to 4.x and make all tasks synchronous.  I'm actually surprised we haven't hit other issues in the build process.

**Comment by gortok** [comment]
@nraboy  I see 3.9 on npm; I don't see a 4.0 yet.https://github.com/gulpjs/gulp

**Comment by nraboy** [comment]
Lame, so all the forums I've read must be referring to what is coming soon on the Gulp timeline.  I had figured it was already out.

**Comment by matheusrocha89** [comment]
@nraboy 4.0 i think is WIP yet, there is a branch on gulp called 4.0.

**Comment by nielskrijger** [comment]
Thank you all for the fast response and the quick investigation!

I don't fully understand the cause yet, but I am truly grateful.

As submodules appear to be a recent introduction to this project, I have always been told to stay away from them. 
I never asked my colleagues why, I never investigated them because I never felt the need to. I did a quick g00gle search;

- http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/
- http://blogs.atlassian.com/2013/03/git-submodules-workflows-tips/#tip5
- https://codingkilledthecat.wordpress.com/2012/04/28/why-your-company-shouldnt-use-git-submodules/

I didn't read them thoroughly but it feels like submodules do have some pitfalls.

Given ng-cordova's unique project nature git submodules might very well be the right way to go. 

I've not looked into ngCordova's integration strategy, but a switch to submodules appears to be more of a minor or major version upgrade rather than a patch upgrade?

If you feel the need for more information of submodules, I'll gladly assist in doing some  research. But as I've said, I'm no expert.

**Comment by nraboy** [comment]
@nielskrijger I personally think it is dependent on contributor buy in.  For example, not all plugins included in ngCordova were built for AngularJS.  That is why people have created wrappers for them.  Because of this you cannot just go ahead and include someones Apache Cordova plugin as a submodule because if they introduce breaking changes, you won't have a way to stop it.  So one of two things would need to happen:

1. All plugins get split into separate ngCordova repositories, ex: ng-cordova-pluginnamehere and then that gets included in ng-cordova via a git submodule.  Then people can contribute fixes to the particular plugin rather than the entire ngCordova repository
2. Only plugins designed for AngularJS get pulled out and added to ngCordova.  For example my ng-cordova-oauth plugin was designed for AngularJS.  That is why it works as a submodule.

I'm very strict in my library.  I deny pull requests all the time in order to keep it working flawlessly.  Other repository owners may not be this strict.

Just my two cents.

**Comment by mhartington** [comment]
No submodules. 
Too many moving parts for little to no gain. 

If people have their own plugin wrapper they want to contribute, they can make a PR to add them to ngCordova, or maintain their own repos.

**Comment by nraboy** [comment]
Traumatic experience with submodules @mhartington?

The gain would be that ngCordova might get more buy in from developers who don't want to (a) manage and support their libraries in two repositories (b) drop their repository and only contribute to ngCordova.

Unless Ionic gets a fleet of internal developers working on this project, ngCordova will only be as good as the contributions it receives.  The last few months have proven not so good.  For example, isn't SQLite still majorly broken in ngCordova?

Just trying to help fix the shaky past that this library has had.

**Comment by gortok** [comment]
> Unless Ionic gets a fleet of internal developers working on this project, ngCordova will only be as good as the contributions it receives. 

That's true; and that's why I want people to give us PRs instead of just raising issues.  It's easy to say, "you need to do this", it's harder to say, "This is an issue; and I don't know how to help, but I want to."

ngCordova only succeeds if we do the latter.  If this were a project with one or two plugins, that'd be one thing -- but ngCordova supports lots of plugin wrappers for 64+ plugins; not all of which have community support behind them.

Submodules mean not knowing when there's an unstable build; and with the free time we have, it can't be spent tracking down unstable builds because a submodule was updated and we have no Issue tracking/commit tracking in this repository to see what changed upstream.  It'd be great if the tooling were there, but it's not.

> The last few months have proven not so good. For example, isn't SQLite still majorly broken in ngCordova?

The last few months haven't been so awesome; you're right. That's partly why I stepped up.  I rely on ngCordova, and I'm not the only one.  I bet there are dozens of companies building Apps that need what ngCordova provides.  We've got to ensure ngCordova is stable. If you rely on ngCordova, then your help is desired.  Submit PRs, even if it's just a PR to make documentation better.

As far as last night's submodule fun, I won't just be merging PRs to mainline; and there will be development branches; more on that to come.   I'm still on week one here; so expect a little shakiness.

As far as SQLite goes; I'm using that plugin next, so unless someone else gets to it first, I'll be able to see pretty quickly what's broken with it.  

Part of this being an open source project means that anyone who can read these pages can help make it better.   Be the change you wish to see in the world.
