### ISSUE TITLE
New Phonegap Push Plugin

### ISSUE THREAD

**Issue by barryvdh** [driftyco/ng-cordova#919]
There is now this Push Plugin: https://github.com/phonegap/phonegap-plugin-push

It seems to have a more consistent API and data object. Also newer options (Android icon image support etc). But it is Cordova 5.x only.

Would this replace the current version? Or would this need a seperate plugin?

**Comment by gortok** [comment]
We've talked about this elsewhere, specifically in #873.  What to do about hosting different versions of Cordova compatible plugins?  This requires a little design work and some thought, but I have some ideas around this. In the meantime; the best way to get a plugin included (no matter if it exists or not), is to create a PR that has an implementation + docs for that implementation.

**Comment by barryvdh** [comment]
And how should I name it? `$cordovaPush2` sounds a bit weird..

**Comment by gortok** [comment]
Yea; lets stay away from that as much as possible (same with 'newMedia' [just learned my lesson there]). As a working title, $cordovaPushv5 would work; we'll rebase if the better solution comes along before you're done with your PR.

**Comment by JavierMartinz** [comment]
:+1:

**Comment by Ionitron** [comment]
Greetings @barryvdh!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
