### ISSUE TITLE
iOS 8.4.1 - Links not opening

### ISSUE THREAD

**Issue by andrewglancy** [driftyco/ng-cordova#938]
After the upgrade to iOS 8.4.1 links are not responding to tap in our ngCordova apps. After exploring we found the note included in the iOS 8.4.1 security release notes. We have been able to fix the issue with a library called https://github.com/ftlabs/fastclick . 

<b>Are other's seeing issues tapping <a> links in iOS 8.4.1 and if so is there a proper solution to this issue?</b>

<b>Below is a screenshot of the change in Apple's 8.4.1 release notes. Their resolution note reads: "Description: An issue existed in how synthetic clicks are generated from tap events that could cause clicks to target other pages. The issue was address through restricted click propogation."</b>

<img width="744" alt="screen shot 2015-08-16 at 10 23 17 am" src="https://cloud.githubusercontent.com/assets/6942888/9294172/38dea5e6-4413-11e5-9838-133b97c2ba4b.png">

**Comment by mhartington** [comment]
Hmm, are you seeing this using ionic as well?

**Comment by andrewglancy** [comment]
@mhartington - We are just using the ngCordova extensions directly. We are not using ionic.

**Comment by mhartington** [comment]
Hmm, alright. Just to be sure, can you give this a try without ngcordova and just use the raw cordova api. Ngcordova shouldn't be messing with click/touch events, so I'm not sure the issue is here.

**Comment by Ionitron** [comment]
Greetings @andrewglancy!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
