### ISSUE TITLE
$cordovaFile

### ISSUE THREAD

**Issue by zeeshanjan82** [driftyco/ng-cordova#940]
I have a requirement where I need to play a ringtone which is already shipped by default with android phone. I am building an cordova app using angular and ng-cordova and do not want to ship .mp3 files with my app instead would like a fixed ringtone to be played on the click of the button. 

My question is can $cordovaFile access the folder on android were the ringtones are stored and can I be able to get the file location of any ringtone so that I could pass it then to  cordova media plugin to play the sound.

**Comment by Ionitron** [comment]
Greetings @zeeshanjan82!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
