### ISSUE TITLE
IOS pushnotification sound

### ISSUE THREAD

**Issue by Alphatiger** [driftyco/ng-cordova#944]
In NgCordova push notification sample code

  $rootScope.$on('$cordovaPush:notificationReceived', function(event, notification) {
      if (notification.alert) {
        navigator.notification.alert(notification.alert);
      }

      if (notification.sound) {
        var snd = new Media(event.sound);
        snd.play();
      }

A sound file is being played explicitly, is this mandatory or if i skip it will it play the default sound?
And does the sound plays (default or custom) plays in background?

I tested with all possibe scenarios but but currently with out the above sound code, sound is not playing

Is the above code mandatory

**Comment by Ionitron** [comment]
Greetings @Alphatiger!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
