### ISSUE TITLE
CardIO is missing as ngCordova.plugins dependency

### ISSUE THREAD

**Issue by fmaceachen** [driftyco/ng-cordova#948]
I´m working on ngCordova 0.1.20-alpha and ngCordova.plugins.cardIO is not being set as a dependency of 'ngCordova.plugins'.

Regards.

**Comment by Ionitron** [comment]
Greetings @fmaceachen!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
