### ISSUE TITLE
cordova-progressIndicator in android is not working

### ISSUE THREAD

**Issue by match08** [driftyco/ng-cordova#949]
cordova-progressIndicator in android is not working,ios working

**Comment by gortok** [comment]
What device are you testing against in Android and what is the Android version on that device?  Can you provide a link to a clean repo that reproduces this issue?

**Comment by match08** [comment]
My device is chinese xiao mi 2 , android is 4.1.   cordova-progressIndicator  some  api  not woring android, ios is woring.   i look this http://paolobernasconi.com/cordova-progressIndicator/
cordova-progressIndicator  Android so coming soon.

**Comment by Ionitron** [comment]
Greetings @match08!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
