### ISSUE TITLE
PushPlugin: foreground not working on iOS

### ISSUE THREAD

**Issue by Heshyo** [driftyco/ng-cordova#955]
I correctly receive notifications on iOS and Android when the app is not started or in background, but when the app is in foreground, my event is only called on Android, not on iOS (iPhone 4S on iOS 6.1.2 and 8.4.1).

Has anyone experienced this? Are foreground notifications on iOS supposed to be handled differently?

**Comment by gortok** [comment]
Can you provide a link to a github repo that reproduces this issue minimally?  ionic start myApp blank and provide the code that you see caues this? It'll help us investigate and fix this issue if it's in ngCordova faster.

Another question to ask; do you see this when you use the cordova plugin directly, instead of the wrapper?

**Comment by Ionitron** [comment]
Greetings @Heshyo!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
