### ISSUE TITLE
do i still need to put my code in device ready 

### ISSUE THREAD

**Issue by awebdeveloper** [driftyco/ng-cordova#962]
As per this http://blog.ionic.io/moving-forward-with-ngcordova/ you ppl had plans to remove this.

So is it done coz the doc still says to put it in device.ready

**Comment by mhartington** [comment]
This has not been added in yet. 

Mike Hartington

**Comment by Ionitron** [comment]
Greetings @awebdeveloper!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
