### ISSUE TITLE
cordova-open instead of cordova-plugin-file-opener2?

### ISSUE THREAD

**Issue by sidlauskaslukas** [driftyco/ng-cordova#967]
What do you think about using cordova-open plugin instead of cordova-plugin-file-opener2? cordova-plugin-file-opener2 has critical issue which makes this plugin not usable to me: you are not able to attach files to email on iOS using Mail.app and no one is fixing this https://github.com/pwlin/cordova-plugin-file-opener2/issues/17 (this issue was opened on Dec 5, 2014)

**Comment by Ionitron** [comment]
Greetings @sidlauskaslukas!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
