### ISSUE TITLE
$cordovaGoogleAnalytics docs source link incorrect

### ISSUE THREAD

**Issue by willmore** [driftyco/ng-cordova#968]
The "Source" link on http://ngcordova.com/docs/plugins/googleAnalytics/ incorrectly points to:

https://github.com/driftyco/ng-cordova/blob/master/src/plugins/ga.js

The link should point to:

https://github.com/driftyco/ng-cordova/blob/master/src/plugins/googleAnalytics.js

**Comment by Ionitron** [comment]
Greetings @willmore!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
