### ISSUE TITLE
Custom build tool has invalid output

### ISSUE THREAD

**Issue by bluehayes** [driftyco/ng-cordova#969]
Visit http://ngcordova.com/build/, then select the dialogs module and hit build.

The output contains:

```
angular.module('ngCordova.plugins', [
	 'dialog'
]);

//#### Begin Individual Plugin Code ####

// install   :     cordova plugin add cordova-plugin-dialogs
// link      :     https://github.com/apache/cordova-plugin-dialogs

angular.module('ngCordova.plugins.dialogs', [])
```

but should be:

```
angular.module('ngCordova.plugins', [
	 'ngCordova.plugins.dialogs'
]);

//#### Begin Individual Plugin Code ####

// install   :     cordova plugin add cordova-plugin-dialogs
// link      :     https://github.com/apache/cordova-plugin-dialogs

angular.module('ngCordova.plugins.dialogs', [])
```

The `ngCordova.plugins` module has the wrong name for `ngCordova.plugins.dialogs`.

Thanks

**Comment by Ionitron** [comment]
Greetings @bluehayes!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
