### ISSUE TITLE
Front camera flipps the picture.

### ISSUE THREAD

**Issue by leitom** [driftyco/ng-cordova#971]
The picture taken by the front(only) camera get's flipped.

Have tried using the property: correctOrientation: true but that does not work.

Tested on android(latest) and ios(latest).

**Comment by Ionitron** [comment]
Greetings @leitom!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
