### ISSUE TITLE
[Bug] duplicate decalration:"version" found in ng-cordova-mocks.js

### ISSUE THREAD

**Issue by lulee007** [driftyco/ng-cordova#972]
in line 604 and line 615 duplicate decalration of `version`?
line 615 should be `manufacturer`?
```javascript
manufacturer:manufacturer
```
![unknown](https://cloud.githubusercontent.com/assets/5875280/9805748/53bc299a-586f-11e5-994b-37f9fb8b110d.png)

**Comment by Ionitron** [comment]
Greetings @lulee007!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
