### ISSUE TITLE
Showing a QR code in email(Gmail) body using social sharing

### ISSUE THREAD

**Issue by bmwertman** [driftyco/ng-cordova#979]
I'm using the ng-cordova social sharing plugin to generate a pre-filled email to send. 

I want to include a QR Code generated using [angular-qr](https://github.com/janantala/angular-qr). It seems that Gmail is blocking it due to the lack of a `src=" "` attribute in the `<qr></qr>` tag directive.

 Any ides for a way around this?

**Comment by Ionitron** [comment]
Greetings @bmwertman!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
