### ISSUE TITLE
documentation geolocation error 

### ISSUE THREAD

**Issue by andel7** [driftyco/ng-cordova#980]
Documentation says that getCurrentPosition(options) - Returns Object with user information, such as id, lastName  - I think it might be a mistake.
http://ngcordova.com/docs/plugins/geolocation/

**Comment by Ionitron** [comment]
Greetings @andel7!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
