### ISSUE TITLE
Camera crashing app

### ISSUE THREAD

**Issue by Kratos-SA** [driftyco/ng-cordova#996]
The camera works great on newer devices like samsung S5; but on crashes on less advanced phones. the phone its crashing on is running android 4.4.4 is there anything I can do to fix this?

I have read up and it seems that this is a plugin that is supposed to stop the app being closed by android. https://code.google.com/p/foreground-camera-plugin/. But which plugin do I use?

**Comment by Ionitron** [comment]
Greetings @Kratos-SA!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
