### ISSUE TITLE
CordovaKeyboard does not work in latest plugin version

### ISSUE THREAD

**Issue by stevenaanen** [driftyco/ng-cordova#997]
Keyboard plugin in it's latest version 1.0.6 changed the package name from `com.ionic.keyboard` to `ionic-plugin-keyboard`, and the Github repo URLs have changed as well. This seems to result in runtime errors and the calls to `$cordovaKeyboard` fail.

Small note: the authors of the [plugin](https://github.com/driftyco/ionic-plugin-keyboard) did not tag the latest version, so it's only in the `package.json`.

**Comment by stevenaanen** [comment]
These are the specific errors I get during runtime:

[2701:1373169] ERROR: Method 'init:' not defined in Plugin 'Keyboard'
[2701:1373169] -[CDVCommandQueue executePending] [Line 159] FAILED pluginJSON = ["Keyboard1626996265","Keyboard","init",[]]

**Comment by fxckdead** [comment]
@stevenaanen did you found some solution to this? ):

**Comment by stevenaanen** [comment]
@fxckdead not yet, I didn't dive into how cordova plugins are structured so I'm not sure, but I guess it has something to do with [this commit](https://github.com/driftyco/ionic-plugin-keyboard/commit/b460a7219c7272ad9f086d9adc012f047dd7687c) from the plugin.

For my project I just downgraded the plugin to 1.0.4 for the moment to keep it working.

**Comment by ymc-sise** [comment]
Same error for me. Obviously I do a downgrade now.

**Comment by Ionitron** [comment]
Greetings @stevenaanen!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
